version: '2'
services:
  selenium:
    image: elgalu/selenium
    environment:
      VNC_PASSWORD: "hunter2"
      NOVNC: "true"
    ports:
      - 4444:24444
      - 5900:25900
      - 6080:26080
    volumes:
      - /dev/shm:/dev/shm

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  web:
    image: registry.kronkltd.net/kronkltd/jiksnu:feature-entrypoint
    depends_on:
      - mongo
    environment:
      JIKSNU_DB_NAME: "jiksnu_docker"
      DOMAIN: jiksnu.localtest.me
    ports:
      - "8080:8080"

volumes:
  mongo-data:
    driver: local
